// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web {
    return FirebaseOptions(
      apiKey: dotenv.env['FIREBASE_WEB_API_KEY'] ?? '',
      appId: '1:441772492413:web:7b161e1eba8aaca5bd5314',
      messagingSenderId: '441772492413',
      projectId: 'kidsync-5fbc3',
      authDomain: 'kidsync-5fbc3.firebaseapp.com',
      storageBucket: 'kidsync-5fbc3.firebasestorage.app',
      measurementId: 'G-WBK44XB5L8',
    );
  }

  static FirebaseOptions get android {
    return FirebaseOptions(
      apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY'] ?? '',
      appId: '1:441772492413:android:fb4f99e087fb6360bd5314',
      messagingSenderId: '441772492413',
      projectId: 'kidsync-5fbc3',
      storageBucket: 'kidsync-5fbc3.firebasestorage.app',
    );
  }

  static FirebaseOptions get ios {
    return FirebaseOptions(
      apiKey: dotenv.env['FIREBASE_IOS_API_KEY'] ?? '',
      appId: '1:441772492413:ios:1b31a740b97bc2f4bd5314',
      messagingSenderId: '441772492413',
      projectId: 'kidsync-5fbc3',
      storageBucket: 'kidsync-5fbc3.firebasestorage.app',
      iosBundleId: 'com.example.kidsync',
    );
  }

  static FirebaseOptions get macos {
    return FirebaseOptions(
      apiKey: dotenv.env['FIREBASE_IOS_API_KEY'] ?? '',
      appId: '1:441772492413:ios:1b31a740b97bc2f4bd5314',
      messagingSenderId: '441772492413',
      projectId: 'kidsync-5fbc3',
      storageBucket: 'kidsync-5fbc3.firebasestorage.app',
      iosBundleId: 'com.example.kidsync',
    );
  }

  static FirebaseOptions get windows {
    return FirebaseOptions(
      apiKey: dotenv.env['FIREBASE_WEB_API_KEY'] ?? '',
      appId: '1:441772492413:web:499baebfff454e76bd5314',
      messagingSenderId: '441772492413',
      projectId: 'kidsync-5fbc3',
      authDomain: 'kidsync-5fbc3.firebaseapp.com',
      storageBucket: 'kidsync-5fbc3.firebasestorage.app',
      measurementId: 'G-110JXHEM4G',
    );
  }
}
